#! /bin/sh
#

AFTERIMAGE_LIBS="-L/usr/local/lib -lAfterImage  -L/opt/local/lib -lfreetype -lz -lbz2 -lz -lm"
AFTERIMAGE_LIBS_EXTERNAL="-L/opt/local/lib -lfreetype -lz -lbz2  -lz -lm"
HAVE_AFTERBASE="no"
AFTERIMAGE_PREF_FORMAT="png"

export AFTERIMAGE_LIBS
export AFTERIMAGE_LIBS_EXTERNAL
export HAVE_AFTERBASE
export AFTERIMAGE_PREF_FORMAT

if test "x$1" = "x--external-only" ; then
	echo $AFTERIMAGE_LIBS_EXTERNAL
else
  if test "x$1" = "x--have-afterbase" ; then
	echo $HAVE_AFTERBASE
  else
        if test "x$1" = "x--preferred-image-format" ; then
                echo $AFTERIMAGE_PREF_FORMAT
        else
                echo $AFTERIMAGE_LIBS
        fi
  fi
fi
exit 0
